[package]
license = "Apache-2.0 OR MIT"
name = "crfsuite-sys"
version = "0.4.3-pre"
authors = ["Thibaut Lorrain <thibaut.lorrain@snips.ai>"]
edition = "2018"
links = "crfsuite"

[build-dependencies]
cc = "1.0"
bindgen = "0.65"
dinghy-build = "0.4.21"

[dependencies]
libc = "0.2"
